"""
Django settings for micolegio project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import binascii

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qnl2@24y2=w_!f%-z#j2)anglfy*=&+3v&*b4k(iaa4k=6%_yf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# ALLOWED_HOSTS = ['52.39.164.228','www.cigreenmetalnomina.com']
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.director',
    # 'apps.profes',
    # 'apps.padres',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'micolegio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'micolegio.wsgi.application'


CACHE_BACKEND = 'simple://'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': 'miColegio',
       'USER': 'postgres',
       'PASSWORD': '80777727',
       'HOST': '127.0.0.1',
       'PORT': 5432,
   }
}

##ec2
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'miColegio',
#         'USER': 'alejandro',
#         'PASSWORD': 'Martin80777727',
#         'HOST': '127.0.0.1',
#         'PORT': '',
#     }
# }




# AUTH_USER_MODEL = 'director.User'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


###############smtp amazon web service
EMAIL = 'superadmin@phiaxioma.com'     ## Para pruebas webescuela@webescuela
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'AKIAIA4GKMT32LP3WIYQ'
EMAIL_HOST_PASSWORD =  'AkK2Dyd/LsScZQepp5WvsBWejpvFkAacZqaWumUmUzuI'
EMAIL_USE_TLS = True

####unica key
def KEY(longitud):
    return binascii.hexlify(os.urandom(longitud)).decode()


###Settings para servidor local
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'staticfiles'),
)

#ec2
# STATIC_URL = '/staticfiles/'
# STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
#
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR,'staticfiles'),
# )
